#include <cstdlib>
#include <iostream>
#include <string>
#include <windows.h>
#include <stdlib.h>
#include <time.h>  
using namespace std;
string i_l_u[12];
string nowy[12];
void klatka_1(){
  cout<< "                                                                    \n                                                                    \n                                                                    \n                        :N               .                          \n                       .M,O. MSUZBr   ,7jXB                         \n                       N: BM20 Li M8JqY,. ji                        \n                       B0r:         ;i JX M.                        \n                     7U:               i.B7                         \n                    qU:          iu.     ,M                         \n                   B7YB5  :q.    kB8,.    :B                        \n                  B7..  :LPGYU:    .:.     UF                       \n                 U1      r  :r              B.                      \n                 M.                         rE                      \n                 O:                          B.                     \n                 :M                          7q                     \n                  07                          B                     \n                  .B                          q7                    \n                   B.                         :G                    \n                   5v                          B.                   \n                   7P                          JBj.                 \n                   .B                            :USL .vj  .        \n                    B.                              iNB:LZLuZ.      \n                    0r                                iE    5u      \n                    7P                                 :B   :Mr     \n                    .B                                  FS   G7     \n                     B.                                 .B   B      \n                     Y5                              .,. Gr  B.     \n                      B                            ..,.. jY BU      \n                      j2                         ..,,... UBUY       \n                       Br                    ..,,:.,... .O          \n                     :uuB;        . . ....,.,.,......  .BX..,.:rBi  \n                   YNY   8U  ......,................ .JP. :rr7i:BB  \n             2X  i8v      iBB,    .............    :UXMU         :  \n             YBBMJ        2Y:5FY;:.           .:ruSSi  ,kF,         \n               ..       .B:    :7JF21uuYYYjUFU5J7,       ,11L:      \n                        B.           ..,.,..                .iBB    \n                    kBBB:                                     B7    \n                     .NU                                            \n                                                                    \n                                                                    \n";
}
void klatka_2(){
  cout<< "                                                                    \n                                                                    \n                      .J2     v                                     \n                     YL,P2FP7B00:  iYLruS                           \n                    jk,EFi2, : .S2GL... M                           \n                   .ZF:          ., :Z.2:                           \n                  vv                  LB                            \n                 qLU7    .    iBu      UY                           \n                M7:BF  .Mi    ,MG:,     Gi                          \n               Zr    .7UB01r     .       B                          \n              ;k          .              v5                         \n              Ur                          M.                        \n              iS                          L2                        \n               M,                          M                        \n               ,O                          U7                       \n                0:                         :E                       \n                LY                          M                       \n                ,0                          25                      \n                 O                           U1L:                   \n                 E,                            :Lkr.:r              \n                 jL                               iBP,0J17          \n                 :k                                 j7   MU         \n                  M                                  Xr   jU        \n                  N:                                 .B.   M:       \n                  LU                                . q7  .0        \n                   M                              .,. rP   B,       \n                   S7                           ..... ,q :O,        \n                    M                        ..,..... i87Y   i      \n                    .q                  . ..,.,.....  BL::77rBB.    \n          YBBi .,::i,GB.   . . ........,..........  ,Z:      .2:    \n           :P0Lrri:.  :qr    ............ . . .   ,5B               \n                   .    Y8YL:      ... . .     .i1U;iLvr,.          \n                  7BBUr7rLYXqL7i:..     ..,:rLUuL.    .:777Bq       \n                   :Li       .:rvjjuJuYuJUL7i,             5B.      \n                                                                    \n                                                                    \n                                                                    \n                                                                    \n                                                                    \n                                                                    \n";
  }
void klatka_3(){
  cout<< "                                                                    \n                   .                                                \n                  0Xu  r7 i5      :F5                               \n                 ur BPLB:Gk;Mv.:jL: 5,                              \n                 Z1vq:..    :7SX .r X:                              \n                Y1:              F7ju                               \n              i5.                  1S                               \n             JUrBu   ,.    0B2      U2                              \n            YZ.iu.  JB. ,   L7i.     Mi                             \n           :O ..  .SBBBM.    ...     .B                             \n           E:        ii               2Y                            \n           O.                          B                            \n           LF                          UJ                           \n            M.                         .M                           \n            i0                          G:                          \n             B                          rX                          \n             ki                         .B                          \n             LU                          8B.                        \n             .8                           7U17.  ..                 \n              M                              rU1E7E5rj7             \n              G:                               .Gr .. E7            \n              Lu                                 1j   iE            \n              :G                                  Oi   NX           \n               B                                  :B  .B            \n               Fv                               .  O:  G.           \n               ,O                              ,.. Uv JM            \n                Gi                           .,... 7S:E   58F       \n                 B                       ....,...  MBFiivULBN       \n                 .B                   ..,.,.,..   U5. .             \n                .7GM.    . ........,.,.,...... ,7Mk      :          \n              r5j.  Pv. . ........... . . .   ,XBY;vJYjYrBBY        \n          ,BBBj      EBBE,                .:7k1:         .ku        \n               .. iUj,  iY1Uj7r::,:,::r7jU5Jr                       \n               BBBr.        .:;77YvL77;i.                           \n                                                                    \n                                                                    \n                                                                    \n                                                                    \n                                                                    \n                                                                    \n";
}
void klatka_4(){
  cout<< "                                                                    \n                                                                    \n                                                                    \n                    7uS  . 7P,     ::i                              \n                  :U,:G1BY7B:XL :Uv::Lq                             \n                  8Urk: .     ikk .v rY                             \n                 71:              ri:F                              \n               :U:                  2E                              \n              7F;B5   ,.    UBN..    rk                             \n             rN.:L. .JBi..   ;i:.     F7                            \n            ,Z     .Y55UU.             O                            \n            1i                         7U                           \n            P:                          M                           \n            iX                          72                          \n             0:                          G                          \n             .N                          5i                         \n              E.                         :N                         \n              j7                          G                         \n              i2                          2k.                       \n               Z                           :L27.                    \n               N.                             :Juj7Yi,.             \n               Fi                                Pu LrLX            \n               i5                                 7U   SF           \n               .E                                  S7   :0          \n                Z.                                 .M   ,N          \n                vY                               .. X;   Z          \n                .8                             .... vj  YZ          \n                 F7                          ...... iEiXj           \n                  O.                      ..,.....  S7,.            \n                   G               . ....,.,....   uM. ....::       \n                   ,B:  . ................... .  iNv .:i;iirBB      \n                  :5:2U,   ....... ... ... .   ,YZ57,       iU      \n                 2U   .72Er                 :rUui   iYji.           \n             kBB5:     :P7ruJJ7ri:,:,::rrLYuvi         i7JLr        \n              ir      kL     .::rr7r7;ri:.                :BS       \n                    :E,                                    2Y       \n                 .BB0                                               \n                                                                    \n                                                                    \n                                                                    \n";
  }
void klatka_5(){
  cout<< "                                                                    \n                                                                    \n                                                                    \n                       i                                            \n                      uXk. ,1::kr     :JM.                          \n                     ,N YBrBrLM:qE::Yj: iU                          \n                     rB7F;..     iLZ, U :F                          \n                    75i              iJr8                           \n                  .Xi                  :B                           \n                 :MiBB   ::    iBB..    .B                          \n                ,B:,7: ,;BU.:   :ri,.    r8                         \n                B.     jr iq:             G;                        \n               7S                         .M                        \n               Yu                          qr                       \n                B                          .B                       \n                J5                          E:                      \n                 B.                         rX                      \n                 2Y                          B                      \n                 :N                          0i                     \n                  M                          iB7                    \n                  M.                          .L5Ui   i             \n                  27                             .L1BULMvu1.        \n                  rS                                Lk  . iO        \n                   M                                 ,M    B:       \n                   M.                                 rG   rB       \n                   1v                                  B:  E:       \n                   ,O                               .. YP  YU       \n                    M,                             ,.. :G :B:       \n                    iE                          ..,... .BrB,        \n                     qY                      ..,.,.... UZ:          \n                      M;              ......,.,...... 7O            \n                       Z2  . ..........,.,........   2F             \n                       kqXi    .......... .....   .LFqL.            \n                      O:  iBB:.               .:7FU01  L1r          \n                     E7   .Z,iuU1YLri::::i77uU1Jr.  i0.  iBu        \n                    jU   .B      ,:rr777rri:.        .qL  B8        \n                 .BBB    M,                            iB:          \n                 .ri  iBB7                             iBN          \n                      :q7                                           \n                                                                    \n";
  }
void animacja_1(){
  for(int i; i<10000;i++){
  klatka_1();
  Sleep(100);
  system("cls");
  klatka_2();
  Sleep(100);
  system("cls");
  klatka_3();
  Sleep(100);
  system("cls");
  klatka_4();
  Sleep(100);
  system("cls");
  klatka_5();
  Sleep(100);
  system("cls");
}}
void animacja_2(){
nowy[0] = "\n" ;
nowy[1] = ". .    2P     GY     SX     :Mi    ;M.    :M:      \n    i:,LY::i::YY::::,YYi:i::iur:::,rJr,i::iui,i.   \n.   B   ..     ..     ..      ,      ,      . :B:  \n.   0 .BB,   rBM    ,BB,    FBE    BB2    qBF  BU. \n.   Z  UL    .Xi    .1v     iF,    v2.    ;F.  BU  \n    0                                          BJ  \n.   G                                          Bu  \n    E                                          BJ  \n.   Z                                          Bu  \n.   E                                          BJ  \n.   G               i::::::::i,                Bu  \n    0              .5L7L7v7LvUr                BJ  \n.   8               Fvv7rir7vJr                Bu  \n    E                  ir;7:                   BY  \n.   Z                  :7iL.                  ;BY  \n    E                  i7rv,                ,:BBL  \n.   G                  i7iL.              :v::LBJ  \n    0                  i7rv,            ,Lr  Y BY  \n.   G                  i7iY,          iY7.  r: Bu  \n.   E                  i7;v:       .iji     S  BJ  \n.   G                  :7iL.     :YYi      G.  BU  \n    0                  :ri7.   iLr.      .qi   BJ. \n.   G               Jrrr;:i7Uk2i.      ..Y5    Bu  \n    E              .SYv7vX2Y7,       ,,.rE     BY  \n.   G               i::,;Uvi.      .:,.vB      Bu  \n    E                       :7:  ,::.:YG       BY  \n.   G                         ,Lv...iFr        Bu  \n    N                           Y7 7u.         BJ  \n.   M                            5ri           BU  \n    iUMBBBBBBBBBBBBBBBBBBBBBBBBBZBB08BBBBBBBBBMBi  \n" ;
for(int i; i<10000;i++){
  for(int x=0; x<12;x++){
    cout<< nowy[x];
    Sleep(100);
   system("cls");
}}}
void animacja_3(){
i_l_u[0] = ". .    1N     OJ     kP     :Mi    rB.    :B:   .  \n    i:,LYi:i::YY::i::YYi:i::iu7::i,7jr,i::iUi,i.   \n.   B   .,     ..     ..      ,      ,      . :B:  \n    E .BB:   rBB    ,BB,    kBZ    BB1    0Bk  B2. \n.   G  UY    .Xi     1L     ik:    v5.    ;S.  B2  \n    E                                          Bj  \n.   G                                          Bu  \n    Z                                          BJ  \n.   8                                          BU  \n.   E                                          Bj. \n.   8               i::::::::i,                BU  \n    E              .5YvL7v7LL27                BJ. \n.   8              .FLv7r;r7Lur                BU  \n.   E                  iri7,                   Bj  \n.   8                  :viY.                   BU  \n.   G                  i7;L,                   BJ  \n.   8                  iLiY,                   Bu  \n    E                  ;7;L:                   Bj  \n.   8                  iviY,                   BU  \n.   G                  i7rv:                   BJ  \n.   8                  iviY.                   BU  \n    E                  ir;v.                   BJ  \n.   O               jrr7ri7rrLi                BU  \n    Z              .SJLL7L7LY57                Bj. \n.   8               i:::::::::,                BU  \n.   Z                                          BJ  \n.   O                                          Bu  \n.   Z                                          Bj  \n.   B                                          BU  \n    iUBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBi  \n" ;
i_l_u[1] = ". .    2P     GY     SX     :Mi    ;M.    :M:      \n    i:,LY::i::YY::::,YYi:i::iur:::,rJr,i::iui,i.   \n.   B   ..     ..     ..      ,      ,      . :B:  \n.   0 .BB,   rBM    ,BB,    FBE    BB2    qBF  BU. \n.   Z  UL    .Xi    .1v     iF,    v2.    ;F.  BU  \n    0                                          BJ  \n.   G                                          Bu  \n    E                                          BJ  \n.   Z                                          Bu  \n.   E                                          BJ  \n.   G               i::::::::i,                Bu  \n    0              .5L7L7v7LvUr                BJ  \n.   8               Fvv7rir7vJr                Bu  \n    E                  ir;7:                   BY  \n.   Z                  :7iL.                  ;BY  \n    E                  i7rv,                ,:BBL  \n.   G                  i7iL.              :v::LBJ  \n    0                  i7rv,            ,Lr  Y BY  \n.   G                  i7iY,          iY7.  r: Bu  \n.   E                  i7;v:       .iji     S  BJ  \n.   G                  :7iL.     :YYi      G.  BU  \n    0                  :ri7.   iLr.      .qi   BJ. \n.   G               Jrrr;:i7Uk2i.      ..Y5    Bu  \n    E              .SYv7vX2Y7,       ,,.rE     BY  \n.   G               i::,;Uvi.      .:,.vB      Bu  \n    E                       :7:  ,::.:YG       BY  \n.   G                         ,Lv...iFr        Bu  \n    N                           Y7 7u.         BJ  \n.   M                            5ri           BU  \n    iUMBBBBBBBBBBBBBBBBBBBBBBBBBZBB08BBBBBBBBBMBi  \n" ;
i_l_u[2] = ". .    1N     OJ     MMi ....           rY.M:   .  \n    i:,LYi:i::YY,,.rr7                   7rJi,i.   \n.   B   .,       .JL.  .            ... :i  , :B:  \n.   Z .BB:   iBM7i.  .             ...  2:UBS  B2. \n.   G  UL    ,BP. .              .... .:8 iF.  B2  \n    Z       ir                 ...  .:.iN      BJ  \n.   8     .F;                 ...  .:..LJ      BU  \n    E    rY.                 .... .:,..M       BJ  \n.   Z  rj:                 ....  .:., 2Y       BU  \n    G,r:                 ..... ..:,..7N        Bj  \n    q.                  .....  .:,.,:8         Bu  \n .uX.                 .... .  .:.,::7k         Bj  \nj:..B:77L7;.        ....... ..:.,::.BMi        BU  \n    P     .r7L7;.   .. .   ,::.,:i.kMSM:       BJ  \n    G          :vjJ,  .  .:,:..:i.;BUU0F       BU  \n    Z             ,LY:  .:,:..:i:.MNJ2SZ       Bj  \n.   8               .rJ;..,.,:i:.YBjUU0P       BU  \n.   Z              ..  YU...:i:,:B2UUqM:       Bj  \n.   8               .   7P :i::.BNUFOE:        BU  \n.   Z               ..   qJ:::.5BNZEr          Bj  \n.   8              ....  YN.,.kBGj:            BU  \n    Z             ....   YS.:BBr               Bj. \n.   8            .... .. 5L:BL                 BU  \n    G          ..... .., O7M                   BJ  \n.   8         ...   .,, kB7                    BU  \n    E      ..... ..,,..EBi                     BJ  \n.   8   ...   ..,...i7uJ                       Bu  \n    Z          . ,rL;.                         BJ  \n.   B        ,;i7:                             BU  \n    i2BBBBBBBBBBBG8BBBBBBBBBBBBBBBBBBBBBBBBBBBBBi  \n" ;
i_l_u[3] = ",             ... ,u FX     :Mi    rB.    :Bi   .  \n                  7F.YYi:i::iU7::i,7jr,i::iUi,i.   \n           ......,8   ..      ,      ,      , :B:  \n         .... .:,:G .BB,    kBG    BB1    0BS  B2. \n        ...  .:,.vJ  5v     iS,    L1.    rS.  B2  \n       ...  .:,, B                             BJ  \n      ...  .:,, UY                             BU  \n   .....  .:,..7N                              BJ  \n  ..... ..:,,::M                               BU  \n. .. . ..:.,::Lu                               Bj  \n. . . ..:,,::.X  ,:,.          .:,.            Bu  \n. .. ,::.,:i.Pq108ZM807     iXEOGM8Gj.         Bj  \n. ..:::..:i.iBF21U1USkOG,  XMXkU12FFGMr        BU  \n. .:,:.,:i:.OEJUjUuUjUUNP:50U2uUuUu2UXM:       BJ  \nJ;,.,.,:i:.YBJUuUuUjUjUUFXkU2uUjUjUuUUEF       BU  \n :S...:i::iB5UjUuUu2uUjUU2u2uUuUuUuUu1SZ       Bj  \n. :G.:i:::GJPU2uUuUjUuUuUjUj2jUj2uUuUU0P       BU  \n.  1F::::E. GNU2uUuUuUuUjUjUuUuUuUu2UqM:       Bj  \n.  7Z.:;k:  ,0OF1UUu2jUuUuUu2uUuUU1SOE:        BU  \n.  70.7q      r0GE55U2jUuUu2jUu11NGEr          Bj  \n.  UJiE         :uZEP21uUuUu2UXEGu:            BU  \n.  ZrP             iSOX5UUU1F8Pr               Bj. \n: kBM                ,kGX2FEEi                 BU  \n jB:k                  iZ8OY                   BJ  \nSL  0                   .Gi                    BU  \ni   E                                          BJ  \n    8                                          Bu  \n    E                                          BJ  \n.   B                                          BU  \n    iUBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBi  \n" ;
i_l_u[4] = ". .    1N     OJ     kP     :Mi    rB.    :Bi   .  \n    i:,LYi:i::YY::::,YYi:i::iU7::i,7jr,i::iUi,i.   \n.   B   .,     ..     ..      ,      ,      , :B:  \n.   Z .BB:   rBB    ,BB,    kBG    BB1    0BS  B2. \n.   G  UL    .Pi    .5v     iS,    L1.    rS.  B2  \n    Z                                          BJ  \n.   8                                          BU  \n    Z                                          BJ  \n.   8                                          BU  \n.   Z                                          Bj  \n.   8           .::,.          .:,.            Bu  \n    E         YZGOZM807     iXEOGM8Gj.         Bj  \n.   O       :88F5U1USkOG,  XMXkU12FFGMr        BU  \n.   Z      .8NU2uUuUjUUNP:50U2uUuUu2UXM:       BJ  \n.   8      vOUUuUuUjUjUUFXkU2uUjUjUuUUEF       BU  \n    Z      Sq1uUuUu2uUjUU2u2uUuUuUuUu1SZ       Bj  \n.   8      U8U2uUuUjUuUuUjUj2jUj2uUuUU0P       BU  \n.   Z      .MNU2uUuUuUuUjUjUuUuUuUu2UqM:       Bj  \n.   8       ,0OF1UUu2jUuUuUu2uUuUU1SOE:        BU  \n.   Z         r0GE55U2jUuUu2jUu11NGEr          Bj  \n.   8           :uZEP21uUuUu2UXEGu:            BU  \n    Z              iSOX5UUU1F8Pr               Bj. \n.   8                ,kGX2FEEi                 BU  \n    G                  iZ8OY                   BJ  \n.   8                   .Gi                    BU  \n    Z                                          BJ  \n.   O                                          Bu  \n    E                                          BJ  \n.   B                                          BU  \n    iUBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBi  \n" ;
i_l_u[5] = ". .    2P     GY     SX     :Mi    ;M.    :M:      \n    i:,LY::i::YY::::,YYi:i::iur:::,rJr,i::iui,i.   \n.   B   ..     ..     ..      ,      ,      . :B:  \n.   0 .BB,   rBM    ,BB,    FBE    BB2    qBF  BU. \n.   Z  UL    .Xi    .1v     iF,    v2.    ;F.  BU  \n    0                                          BJ  \n.   G                                          Bu  \n    E                                          BJ  \n.   Z                                          Bu  \n.   E                                          BJ  \n.   G           .::,.          .:,.            Bu  \n    0         LEEG08Zq7     iSN8E8ZEJ.         BJ  \n.   8       :GZ51U2uFSGE,  kOkFU2U55E8r        Bu  \n    E      .GqUUjujuJUUPX:2NUUjUjUjUukM:       BY  \n.   Z      7GUUjujUJuJUu5kFuUjuJUJUjUuN5      ;BY  \n    E      FP2jUjujUjUJUuUjUjUjUjUjUJUF0    ,:BBL  \n.   G      uGUUjUjUJUjUjUJUJUJuJUjujUuP5  :v::LBJ  \n    0      .OqUUjUjUjujUJUJUjUjUjUjUuFq:.7r  Y BY  \n.   G       ,q852UUjUJUjujUjUjUjujUUX0Uir.  r: Bu  \n.   E         rNZN21uUJUjUjUJuJUU1SGqY.    .S  BJ  \n.   G           :jE0XU2jUjUjUu11PGX7.      G.  BU  \n    0              iF8k1uujUUkFXL,       .qi   BJ. \n.   G                ,SESU5X8S7.       ..Y5    Bu  \n    E                  iGM0U:        ,,.rE     BY  \n.   G                   ,B7:.      .:,.vB      Bu  \n    E                       :7:  ,::.:YG       BY  \n.   G                         ,Lv...iFr        Bu  \n    N                           Y7 7u.         BJ  \n.   M                            5ri           BU  \n    iUMBBBBBBBBBBBBBBBBBBBBBBBBBZBB08BBBBBBBBBMBi  \n" ;
i_l_u[6] = ". .    1N     OJ     MMi ....           rY.M:   .  \n    i:,LYi:i::YY,,.rr7                   7rJi,i.   \n.   B   .,       .JL.  .            ... :i  , :B:  \n.   Z .BB:   iBM7i.  .             ...  2:UBS  B2. \n.   G  UL    ,BP. .              .... .:8 iF.  B2  \n    Z       ir                 ...  .:.iN      BJ  \n.   8     .F;                 ...  .:..LJ      BU  \n    E    rY.                 .... .:,..M       BJ  \n.   Z  rj:                 ....  .:., 2Y       BU  \n    G,r:                 ..... ..:,..7N        Bj  \n    q.                  .....  .:,.,:B         Bu  \n .uX.                 .... .  .:.,::U5         Bj  \nj:..B:77L7;.        ....... ..:.,:i:B          BU  \n    P     .r7L7;.   .. .   ,::.,:i:G,          BJ  \n    G          :vjJ,  .  .:,:..:i,2U           BU  \n    Z             ,LY:  .:,:..:i::B            Bj  \n.   8               .rJ;..,.,:i::qi            BU  \n.   Z              ..  YU...:i::Lq             Bj  \n.   8               .   7P :i:::B              BU  \n.   Z               ..   qJ::::Z:              Bj  \n.   8              ....  YN.:iPi               BU  \n    Z             ....   Yk.rq                 Bj. \n.   8            .... .. 5YiG                  BU  \n    G          ..... .., MvE                   BJ  \n.   8         ...   .,, kM7                    BU  \n    E      ..... ..,,..EB:                     BJ  \n.   8   ...   ..,...i7jJ                       Bu  \n    Z          . ,rL;.                         BJ  \n.   B        ,;i7:                             BU  \n    i2BBBBBBBBBBBG8BBBBBBBBBBBBBBBBBBBBBBBBBBBBBi  \n" ;
i_l_u[7] = ",             ... ,u FX     :Mi    rB.    :Bi   .  \n                  7F.YYi:i::iU7::i,7jr,i::iUi,i.   \n           ......,8   ..      ,      ,      , :B:  \n         .... .:,:G .BB,    kBG    BB1    0BS  B2. \n        ...  .:,.vJ  5v     iS,    L1.    rS.  B2  \n       ...  .:,, B                             BJ  \n      ...  .:,, UY                             BU  \n   .....  .:,..7N                              BJ  \n  ..... ..:,,::M                               BU  \n. .. . ..:.,::j5                               Bj  \n. . . ..:,,:i:M ,:::,        ,i:i:             Bu  \n. .. ,::.,:i,8. vY7U7        7JLLj             Bj  \n. ..:::..:i,UU  7rr7r        iL;77             BU  \n. .:,:.,:i::B   r7i7i        ;7rr7             BJ  \nJ;,.,.,:i:,qr   7rr7i        i7i7r             BU  \n :S...:i::vq    r7iLi        ;7rr7             Bj  \n. :G.:i:::B     7rr7;        i7i7r             BU  \n.  1F::::Z:     r7ivi        ;7rr7             Bj  \n.  7Z.:;ki      7rr7r        ivi77             BU  \n.  70.7q        r7iLi        i7rr7             Bj  \n.  UJiE         7rr7i        ivi77             BU  \n.  ZrP          YLrvi        i77LJ             Bj. \n: kBM           iii7L;7r777rrv7:;i             BU  \n jB:k              ;uYLJYJYjYUi                BJ  \nSL  0              .i:::::::::,                BU  \ni   E                                          BJ  \n    8                                          Bu  \n    E                                          BJ  \n.   B                                          BU  \n    iUBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBi  \n" ;
i_l_u[8] = ". .    1N     OJ     kX     :Mi    rB.    :B:      \n    i:,LYi:i::YY::i::YYi:ii:iU7::i,7jr,i::iU;,i.   \n.   B   ..     ..     ..      :      ,      , :B:  \n    Z .BB:   rBB    ,BB,    SBZ    BB5    0BS  B2. \n.   G  2L    .Pi     1L     ik:    v1     rS.  BU  \n    Z                                          Bj  \n.   8                                          BU  \n.   E                                          BJ  \n.   O                                          BU  \n.   G                                          Bj  \n.   8           :::i,        ,i:i:             BU  \n    G           YJ7Ur        7jLYu             BJ  \n.   8           7rr7;        iL;7r             Bu  \n    E           r7ivi        i7rr7             Bj  \n.   8           7rr7;        ivi7r             BU  \n.   Z           r7i7i        ;7rr7             BJ. \n.   8           7rr7;        iL;7r             BU  \n    Z           r7;Li        ;7rr7             BJ  \n.   8           7rr7;        i7i77             Bu  \n    Z           77i7i        ;7rr7             BJ  \n.   8           7rr7i        i7;77             BU  \n.   Z           LY7vi        i77LJ             Bj  \n.   8           iii7L;7r777rrvv:r:             BU  \n.   Z              rjYYJLjYJYUi                Bj. \n.   O              .i:::::::::,                BU  \n.   Z                                          BJ  \n.   8                                          BU  \n    E                                          BJ. \n.   M                                          BU  \n    ;UBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB;  \n" ;
i_l_u[9] = ". .    2P     8Y     Sk     ,Mi    rM.    :M:      \n    i:,LYi:i::LY:::::YY::i::iur:::,rJ;,i::iui.:.   \n.   B   ..     ..     ..      ,      ,      . :B:  \n    0 .BB:   rBB    ,BB,    FBE    BB1    qBF  BU. \n.   Z  UL    .ki     2L     iF:    72     ;F.  BU  \n    E                                          BJ  \n.   G                                          BU  \n.   0                                          BJ  \n.   8                                          BU  \n.   E                                          BJ  \n.   G           ::::,        ,i:::             Bu  \n    E           YY7ur        7JLLJ             BJ  \n.   G           7rr7;        iLi7r             Bj  \n    0           r7i7i        i7;r7             BY  \n.   G           7rr7i        ivi7r            rBY  \n.   E           rri7i        i7;r7          ,:BBv  \n.   G           7rr7;        ivi7r        :L::LBj  \n    E           r7ivi        i7rr7      :Lr  L BY  \n.   Z           7r;7;        i7irr    iY7.  ;: Bj  \n    E           rri7i        ir;;;  iji    .k  BY  \n.   G           7r;7i        :7i72rLi      8.  Bu  \n    0           LLrv:        iLSU:.      .Pi   BJ  \n.   G           ii:rLi7rrir7uX2:       ..Y5    BU  \n    E              ;JYLLYEFj7.       ,,.r0     BJ. \n.   8              .i::,;Uvi.      .:,.vB      Bu  \n.   E                       :7:  ,::.,YG       BY  \n.   G                         ,L7...;Fr        Bu  \n    0                           Y7 7u.         BY. \n.   M                            1r;           BU  \n    iUMBBBBBBBBBBBBBBBBBBBBBBBBBGBB08BBBBBBBBBMBi  \n" ;
i_l_u[10] = ". .    1N     OJ     MMi ....           rY.M:      \n    i:,LYi:i::YY:,,rr7                   7rJ;,i.   \n.   B   ..       .JY. ..            ... :i  , :B:  \n    Z .BB:   iBM7i.  .             ...  2:UBS  B2. \n.   G  2L    ,BX. .              .... .,G iF.  BU  \n    Z       ir                 .... .:.iN      Bj  \n.   8      5r                 ......:,.LJ      BU  \n.   E    rY.                 ... ..:.,.M       BJ  \n.   G  rj:                  ... ..:,, 1Y       BU  \n    G,7:                 .....  .:...7N        Bj  \n    P.                  .....  .:,.,:M         BU  \n .uX.                 ......  .:,,::U5         BJ  \nj:..B:77L7r,        ..... . ..:.,:i:B          Bu  \n    P     .r7L7;.  ..... . ,::.,:i:Z,          Bj  \n    G          :vJJ:  .  .:,:.,:i,2U           BU  \n.   Z             ,7Yi  .:,,..:i::B            BJ. \n.   8               .rYi..,.,:i:,Pi            BU  \n    Z              .   YU...:i::vq             BJ  \n.   8               .   7P :i:::B              Bu  \n    Z               ..   Pj::::E:              BJ  \n.   8              ....  JN.:iXi               BU  \n.   Z             ....   JS.rN                 Bj  \n.   8            ....  . 1YiZ                  BU  \n.   Z          ..... ... M70                   Bj. \n.   O         ... . .., kM7                    BU  \n.   Z      ... . ..,,..EB:                     BJ  \n.   G   ... . ..,...:vjj                       BU  \n    G        .   :rLr.                         BJ. \n.   B        ,;i7,                             BU  \n    i2BBBBBBBBBBBZGBBBBBBBBBBBBBBBBBBBBBBBBBBBBB;  \n" ;
i_l_u[11] = ",             ... :U FX     :Mi    rB.    :B:      \n                  75.YYi:ii:iU7::i,7jr,i::iU;,i.   \n           ......,8   ..      :      ,      , :B:  \n         .... .:,:Z .BB,    SBZ    BB5    0BS  B2. \n        ...  .:..vu  1L     ik:    v1     rS.  BU  \n       ...  .:,, M                             Bj  \n      .... .:,. UY                             BU  \n   .....  .:...vN                              BJ  \n  ..... ..:,,::M.                              BU  \n. ....  .:.,::jk                               Bj  \n. . . ..:.,:i:B     ;::::::::i,                BU  \n. ...,::.,:i,8.    .5YvL7v7LL27                BJ  \n. ..:,,..:i:U2     .FvL7rir7Ljr                Bu  \n  .:,:..:i::B          i7;7:                   Bj  \nJ;:.,.,:i:,q;          :viY.                   BU  \n :k,..:i::7q           i7rL,                   BJ. \n. :8.:i:::B            iLiY,                   BU  \n.  2S::::G:            ;7rL,                   BJ  \n.  7Z.:;ki             iLiY,                   Bu  \n.  7N.7N               i7;L:                   BJ  \n.  UJi0                i7iY.                   BU  \n,  Grq                 i7r7.                   Bj  \n, kMM               jrr7ri777Li                BU  \n JB:S              .SYYL7L7LY57                Bj. \nSL  E               ;:::::::::,                BU  \ni   E                                          BJ  \n    8                                          BU  \n    E                                          BJ. \n.   M                                          BU  \n    ;UBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB;  \n" ;
for(int i; i<10000;i++){
  for(int x=0; x<12;x++){
    cout<< i_l_u[x];
    Sleep(100);
   system("cls");
}}}
int main(){
  cout<<" wybierz | 1: a running alpaca | 2: i love you |  = ";
  int wybor;
    cin>>wybor;
    switch (wybor)
    {
    case 1:
        animacja_1();
        main();
    case 2:
        animacja_2();
        main();
    case 3:
        animacja_3();
        main();
    default:
        cout << "error\n";
        main();
    }
    system("pause");
    return main();
}